server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false
    username: jskodova
    password: jskodova
  jpa:
    properties:
      hiber
  main:
    web-application-type: servlet